// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aBookApp.Data;

#nullable disable

namespace aBookApp.Migrations
{
    [DbContext(typeof(appDbContext))]
    [Migration("20231215021826_ThirdMigration")]
    partial class ThirdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aBookApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("productname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            price = 36,
                            productname = "Mango"
                        },
                        new
                        {
                            Id = 2,
                            price = 34,
                            productname = "Banana"
                        },
                        new
                        {
                            Id = 3,
                            price = 39,
                            productname = "Jute"
                        },
                        new
                        {
                            Id = 4,
                            price = 38,
                            productname = "Cassava"
                        },
                        new
                        {
                            Id = 5,
                            price = 37,
                            productname = "Guava"
                        },
                        new
                        {
                            Id = 6,
                            price = 37,
                            productname = "Rice"
                        },
                        new
                        {
                            Id = 7,
                            price = 37,
                            productname = "Beans"
                        },
                        new
                        {
                            Id = 8,
                            price = 37,
                            productname = "Jute"
                        },
                        new
                        {
                            Id = 9,
                            price = 37,
                            productname = "Apple"
                        },
                        new
                        {
                            Id = 10,
                            price = 37,
                            productname = "Melon"
                        },
                        new
                        {
                            Id = 11,
                            price = 37,
                            productname = "Pear"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
